version: '3.8'

services:
  frontend:
    image: lum1no/deploy-main-06-10_frontend:prod
    ports:
      - "4200:80"
    restart: always

  backend:
    image: lum1no/deploy-main-06-10_backend:prod
    # Убираем публикацию порта 8080, т.к. все идет через nginx
    expose:
      - "8080"
    env_file:
      - ./prod.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    extra_hosts:
    - "llc01.llc.tagras.corp:10.1.4.220"
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
      ollama:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
    restart: always

  node-logger:
    image: lum1no/deploy-main-06-10_back_node_js:prod
    expose:
      - "3001"
    environment:
      - PORT=3001
      - DB=mongodb://mongo:27017/logs_db
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    expose:
      - "11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always

  db:
    image: pgvector/pgvector:pg17-bookworm
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    expose:
      - "5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chatdb
    restart: always

volumes:
  db_data:
  mongo_data:
  ollama_data: