version: '3.9'
services:
  postgres:
    image: pgvector/pgvector:pg17-bookworm
    container_name: knowledge-postgres
    environment:
      POSTGRES_DB: knowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5132:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    # --- ИЗМЕНЕНИЕ: Собираем наш кастомный образ ---
    build: ./ollama-init
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  mongo:
    image: mongo
    container_name: knowledge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  ollama_data:
  mongo_data:
